from node:18 as builder
WORKDIR /app
COPY package*.json .
RUN npm install --forzen-lockfile
COPY . .
RUN npm run build

from nginx:alpine as runner
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]